#!/bin/bash

_asdf_install() {
  _get_tags() {
    curl --silent "https://api.github.com/repos/hashicorp/terraform/tags?page=${1}" \
      | jq -r '.[]
        | select(.name | contains("alpha") | not)
        | select(.name | contains("b") | not)
        | select(.name | contains("dev") | not)
        | select(.name | contains("rc") | not)
        | .' \
      | jq -rs '.[].name' \
      | cut -c 2-
  }

  git clone -c advice.detachedHead=false -q https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.8
  echo 'source ~/.asdf/asdf.sh' > ~/.bashrc && . /root/.asdf/asdf.sh && asdf plugin add terraform

  # versions="$(_get_tags 1) $(_get_tags 2)"
  # for v in ${versions}; do asdf install terraform "${v}"; done
}

_asdf_install
